### ISSUE TITLE
Unit tests that use canned/mocked responses

### ISSUE THREAD

**Issue by hankditton** [aguxez/godfist#4]
It would be great to have some tests that use something like [bypass](https://github.com/PSPDFKit-labs/bypass) to simulate the Riot Server that can be run locally without depending on API keys or Riot's Server state.

**Comment by aguxez** [comment]
I was thinking on doing this but never did. I should've done this since the beginning but never thought about it. I could make a module and implement this as soon as I get my Pc back (Unless you want to _work_ on this). Thanks for pointing this out.

**Comment by hankditton** [comment]
I wouldn't mind doing this, but I don't know if I'll have the time to get to it. I'll post in the issue if I start on it though.

**Comment by aguxez** [comment]
Excellent, thanks!

**Comment by aguxez** [comment]
Done in last version ^-^
