### ISSUE TITLE
Support multiple rate limits

### ISSUE THREAD

**Issue by hankditton** [aguxez/godfist#5]
Since each API key has a short-term and a long-term rate limit (e.g. 20 requests per second or 100 requests per 2 minutes for dev keys) it would be nice to have support for both of them with the built-in rate limiting. 

Also, methods have their own rate-limits on a per-method basis. Support for that could be added as well.

**Comment by aguxez** [comment]
This a good feature than could be added. 
Can you elaborate on your second statement? Thanks! 🙏🏽

**Comment by hankditton** [comment]
For method rate limits, see the "METHOD RATE LIMIT HEADERS" section here: https://developer.riotgames.com/rate-limiting.html.

Essentially each method has their own unique rate limit in addition to your app-wide rate limits. 

For example, each static data endpoint has a rate limit of 10 calls per hour. Even if you haven't hit your application rate limit you still can't make more than 10 requests per hour to a specific static date endpoint.

**Comment by aguxez** [comment]
Ah I see, I was confused for a moment, I will look into this and try to implement a way of handling the rate limits. Thanks again.

**Comment by aguxez** [comment]
Working on this.
